collector_entity:
    resource: "@CollectorEntityBundle/Resources/config/routing.yml"
    prefix:   /

collector_admin:
    resource: "@CollectorAdminBundle/Resources/config/routing.yml"
    prefix:   /

adesigns_calendar:
  resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

dashboard:
    pattern:  /
    defaults: { _controller: SonataAdminBundle:Core:dashboard }

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type:     sonata_admin

sonata_user_admin:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

presses:
    type:     rest
    resource: Collector\EntityBundle\Controller\RestController
    prefix: /rest/

test_post:
    pattern: /rest/test
    defaults: { _controller: CollectorEntityBundle:Test:index}